[package]
name = "example-deep-learning-train-step"
description = "UCF IR example: train step"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish.workspace = true

[[bin]]
name = "example-deep-learning-train-step"
path = "src/main.rs"

[dependencies]
ucf = { workspace = true }
