[package]
name = "ucf-backend-vulkan"
description = "Vulkan backend for UCF (stage 3)"
readme = "README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
ucf-capability = { workspace = true }
ucf-ir = { workspace = true }
ucf-scheduler = { workspace = true }
