[package]
name = "example-simulation-sph"
description = "UCF IR example: SPH"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish.workspace = true

[[bin]]
name = "example-simulation-sph"
path = "src/main.rs"

[dependencies]
ucf = { workspace = true }
