[package]
name = "ucf-backend-dx12"
description = "DirectX 12 backend for UCF (stage 2)"
readme = "README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
ucf-capability = { workspace = true }
ucf-ir = { workspace = true }
ucf-scheduler = { workspace = true }
